pin "firebase/app", to: "https://www.gstatic.com/firebasejs/10.12.3/firebase-app.js"
pin "firebase/auth", to: "https://www.gstatic.com/firebasejs/10.12.3/firebase-auth.js"
pin "@firebase/app", to: "https://www.gstatic.com/firebasejs/10.12.3/firebase-app.js"
pin "@firebase/auth", to: "https://www.gstatic.com/firebasejs/10.12.3/firebase-auth.js"
pin "idb", to: "https://cdn.jsdelivr.net/npm/idb@7.1.1/build/umd.js"
pin "tslib", to: "https://cdn.jsdelivr.net/npm/tslib@2.6.3/tslib.es6.js"
